src/main/res/xml/symbols.xml
src/main/res/xml/symbols_alt.xml

Adding the square root symbol required moving the division symbol to the multiplication symbol key to make room.

Add dash variations and square root symbol to symbol tables

---

build.gradle

since changing that breaks unicode for Android v5
Will fix https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/790

going back to API level v7

---

app/src/main/res/xml/qwerty_with_symbols.xml

Make the order of right parenthesis, square and curly brackets match the
order of left ones, the same way '<' and '«' match their counterparts.

Reorder right parenthesis and brackets

---

app/src/main/res/values/strings.xml
app/src/main/res/values/styles_yochees_keyboard_theme.xml
app/src/main/res/xml/keyboard_themes.xml
app/src/test/java/com/anysoftkeyboard/addons/AddOnsFactoryTest.java

Adds a variant of Yochees Dark theme with hints. Similar to Lean Dark - Option 2

Create variant of Yochees Dark theme with hints

---

app/src/main/res/xml/popup_smileys.xml
app/src/main/res/xml/popup_smileys_short.xml
jnidictionaryv1/src/main/jni/source/dictionary.cpp

This PR adds support for `:D` `B)` and `:O`, which are fairly common smileys (to me, at least) but missing form the stock text smileys. 
I also had to make a small change to get this to compile at all, let me know if that shouldn't be added and I'll trash that commit.
One more point, shouldn't the 'long form' of smileys print out long smileys? Pressing on `:-)` prints out `:)` on the debug build (and that makes sense, since that's how it's listed out in the field), but I have a phone with the stable release that /sometimes/ works? I'm not really sure what's going on there. It doesn't matter too much to me, because shorter smileys rule `:)`
Let me know if anything should be changed, or if you spot anything amiss.

Add a few additional short smileys

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/CandidateView.java

Fix caps lock when gesture typing

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardCapitalizeSelectionWhenShiftPressedTest.java
app/src/test/java/com/anysoftkeyboard/TestInputConnection.java

Pressing the shift key with characters highlighted toggles the characters from uppercase to lowercase, based on whether or not they are currently uppercase or lowercase.
I'm not sure if there should be a preferences toggle to enabled/disable this. If there should be, then that's something I can look into adding.

Switch capitalisation of highlighted word

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/dictionaries/TextEntryState.java
app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetector.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSwitchedListener.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPopText.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/MiniKeyboardActionListener.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/OnKeyboardActionListener.java
app/src/main/java/com/anysoftkeyboard/quicktextkeys/ui/RecordHistoryKeyboardActionListener.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGestureTypingTest.java
app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
app/src/test/java/com/anysoftkeyboard/dictionaries/TextEntryStateTest.java
app/src/test/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetectorTest.java

Deleting a word after an incorrect gesture to try again should now be one keypress away!
TODO:

Delete whole word when deleting a gestured word

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardHardware.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithQuickText.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardQuickTextTest.java

Fix for problem described in #1278
This changes the behaviour of the keyboard slightly when the emoji keyboard is up and hardware back/home buttons are pressed.

Fix Keyboard not Closing when Emojis open

---

app/src/main/res/xml/colemak.xml

ASK's Colemak layout swaps shift and backspace, as noted in issue #998 . This swapped layout does not match the backspace key positioning on the number and symbol input pages, leading to much annoyance.
This PR simply swaps them back to match the symbols page, and all other keyboards.
~The official colemak keyboard layout (colemak.com) does not move the backspace key at all, it is in the default position on the keyboard.~ Actually colemak recommends remapping capslock to backspace, but on an android keyboard this doesn't make much sense.

Fix swapped shift and backspace on colemak layout

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/ext_kbd_top_row_terminal.xml
app/src/main/res/xml/extension_keyboards.xml
app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

Adds a terminal common top row, for terminal use with non-QWERTY layouts, or for people who prefer these keys on top.
See #1443.

Add terminal common top row

---

app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardHardware.java
app/src/main/java/com/anysoftkeyboard/utils/Workarounds.java
app/src/main/res/values-en/strings.xml
app/src/main/res/values/settings_defaults_dont_translate.xml
app/src/main/res/values/settings_keys_dont_translate.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_language_tweaks.xml
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardPhysicalKeyboardTest.java

Issue #111 mentioned that the current shift+space shortcut for switching layouts on physical keyboards was unintuitive, and it is inconvenient when typing capital letters, parentheses, underscores, etc.
This PR adds a toggle in the hardware keyboard settings to disable that shortcut.

Add toggle for physical hardware shift+space layout switch shortcut

---

app/src/main/res/xml/ext_kbd_top_row_terminal.xml
app/src/main/res/xml/terminal.xml

Both terminal layout and recent terminal top row are lacking repeatable flag for arrow keys, so they send the action only once before releasing the key.

Make arrow keys on terminal layout and top row repeatable

---

app/src/main/java/com/anysoftkeyboard/dictionaries/BTreeDictionary.java
app/src/main/java/com/anysoftkeyboard/dictionaries/DictionaryAddOnAndBuilder.java
app/src/main/java/com/anysoftkeyboard/dictionaries/ExternalDictionaryFactory.java
app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java
app/src/main/java/com/anysoftkeyboard/dictionaries/TextEntryState.java
app/src/main/java/com/anysoftkeyboard/dictionaries/content/ContactsDictionary.java
app/src/main/java/com/anysoftkeyboard/dictionaries/sqlite/AutoDictionary.java
app/src/main/java/com/anysoftkeyboard/dictionaries/sqlite/WordsSQLiteConnection.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/CandidateView.java
app/src/main/java/com/anysoftkeyboard/receivers/PackagesChangedReceiver.java
app/src/main/java/com/anysoftkeyboard/ui/tutorials/TutorialsProvider.java
app/src/main/java/com/anysoftkeyboard/utils/IMEUtil.java
app/src/main/java/com/menny/android/anysoftkeyboard/ChewbaccaUncaughtExceptionHandler.java
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/xml/symbols.xml
app/src/main/res/xml/symbols_alt.xml
app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewWithMiniKeyboardTest.java
base/src/main/java/com/anysoftkeyboard/base/utils/CompatUtils.java

This PR is mainly meant to fix auto dictionary. Until now, the option for "Do not learn new words" failed because AnySoftKeyboard naïvely set `mLearnWordThreshold` to -1, forcing it to always learn automatically new words instead. It also reported always the same two states, causing other bugs.
Later, I added little fixes like:
- Adding Greek letters to the default layouts. There is no universal way to map Greek characters to the standard QWERTY keyboard and the characters that were already there didn't seem to match any layout I knew of. I set them up using the Greek layout on Ubuntu as a base, but I noticed that AZERTY users will find Greek letters in different places... so please check into this and swap whatever's needed.
- Adding Lithuanian characters.
- Updating `strings.xml` for …

Fix dictionary auto-learning

---

app/src/main/res/values/styles_aosp_keyboard_theme.xml

Fixes #1884 by allowing the user to chose if they want to display hints or not with AOSP themes

Allow displaying hints with the AOSP based themes

---

app/build.gradle
app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/addons/AddOnImpl.java
app/src/main/java/com/anysoftkeyboard/dictionaries/DictionaryContentObserver.java
app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java
app/src/main/java/com/anysoftkeyboard/dictionaries/TextEntryState.java
app/src/main/java/com/anysoftkeyboard/dictionaries/UserDictionary.java
app/src/main/java/com/anysoftkeyboard/dictionaries/sqlite/SQLiteUserDictionaryBase.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboard.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPopText.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/AnyPopupKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardFactory.java
app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSupport.java
app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSwitcher.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AskGestureEventsListener.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/KeyPreviewsManager.java
app/src/main/java/com/anysoftkeyboard/ui/SendBugReportUiActivity.java
app/src/main/java/com/anysoftkeyboard/utils/LocaleTools.java
app/src/main/java/com/menny/android/anysoftkeyboard/AnyApplication.java
app/src/test/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboardRowsTest.java
base/src/main/java/com/anysoftkeyboard/base/utils/Logger.java
dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/WordComposer.java
gradle/fdroid_yaml_output.gradle

These commits achieve four goals:
1. **Generate unsigned release APKs instead of debug APKs, with `./gradlew assembleRelease`.** Like you asked for at #303, the Gradle scripts for this projecy will now default to unsigned release APKs if no suitable keystore can be found. Debug APKs can still be created with `assembleDebug` and `build`. (I think `build` isn't working right now because of some problem with canary and test releases; I haven't looked into that.)
2. **Fix #1636 and all related bugs.** Basically, most string manipulation functions in Java depend in `char` values, which can each hold a single multi-byte character... until U+FFFF. Some characters have now assigned code-points over U+FFFF, and those can only fit in two `char`s.
Some select functions work with `int` values, which …

Generate unsigned release APKs, fix #971 and #1636

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
app/src/test/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboardTest.java
scripts/ci/ci_check.sh

Fixes #1919
Uses [getType](https://developer.android.com/reference/java/lang/Character.html#getType(int)): a return value of 6 is a [combining non-spacing character](https://developer.android.com/reference/java/lang/Character.html#NON_SPACING_MARK), a value of 8 is a [combining spacing character](https://developer.android.com/reference/java/lang/Character.html#COMBINING_SPACING_MARK). 
I've moved the pull request, but I'm afraid I don't know much about tests/java in general, would I be able to get any help on that?

AnyKeyboard: Combining characters aren't EOW characters

---

addons/CONTRIBUTING.md

These example commands weren't updated when the language
repository was merged back into the main keyboard repo.

doc typo: Include :addons: in gradlew path.

---

addons/languages/german/pack/src/main/res/values-de/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_broad.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_extra.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_slim.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

This patch adds 3 keyboards to the German language addon, each of them offering a QWERTY variant of the existing layouts.
I am not an android developer, so I haven't been able to test this locally. I tried to install the output of the `build` task on my phone but it failed without a helpful error message.
Any pointers on where I can get a build from that I can install on my phone?
Is the CI going to produce artifacts that I can install?

Add German QWERTY keyboards

---

addons/languages/catalan/pack/src/main/res/values/catalan_pack_strings.xml
addons/languages/catalan/pack/src/main/res/xml/catalan_keyboards.xml
addons/languages/catalan/pack/src/main/res/xml/qwerty.xml

Catalan has many words using the middle dot (interpunct) between two L in order to represent the [ɫː] phoneme but when typing a middle dot in ASK it will stop suggesting those words as it does not consider it an inner word character. The same goes with the hyphen, used especially when inflecting verbs.
This PR adds both the middle dot and the hyphen to the IsLetter exceptions and the middle dot as a popup character of the hyphen.

Add middle dot and hyphen-minus as letter exceptions in Catalan

---

api/src/main/res/values/keyboard_theme_api.xml
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/values/styles_base_keyboard_theme.xml
ime/app/src/main/res/values/styles_lean_light_keyboard_theme.xml
ime/app/src/main/res/values/styles_yochees_keyboard_theme.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_aosp.xml
ime/app/src/main/res/xml/extension_keyboards.xml
ime/app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

Adding the bottom row for AOSP/Gboard.
The emoticon icon works same as Gboard (single tap shows the emoticons list), for this reason I had to add an icon for `key_code_quick_text_popup`
I have tested Normal/URL/IM/Email modes and it works almost exactly like Gboard.
I will also post an issue to see if you can help with a couple of things that could be improved.
This related to https://github.com/AnySoftKeyboard/LanguagePack/issues/260 (now archived)

Add: AOSP/Gboard bottom common kbd

---

ime/app/src/main/res/values-es/currency_data.xml
ime/app/src/main/res/xml-es/symbols.xml

Fixes #2074 
Commit [7185d6](https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/7185d6e060cb9db519df0f506927a52f8e160abe) fixes the currency issue.
Commit [07558cd](https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/07558cd2499667e2d83360edffa63c3577632c76) could be improved. 
I think it should not be bound to the locale but to the language addon being used.
If I am italian, and my phone language is set to Italian, when I type in Spanish, I cannot benefit from the easily accessible `¿` and `¡`. These symbols are bound the the language you are writing into, and not to the one set as default language in Android.
I tried to move a modified version of [symbols.xml](https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/ime/app/src/main/res/xml/symbols.xml) to …

Spanish locale

---

.github/workflows/deployment_promote.yml

We need to specify which ref/branch we are using since GH will default to master if the SHA is the master HEAD.

fix deployment ref argument

---

ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java
ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/settings_keys_dont_translate.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/prefs_dictionaries.xml
ime/app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestionsProviderTest.java

Fixes #1879
Fixes #2173
<table>
<tr>
<th>Enabled</th>
<th>Disabled</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/16888339/77706340-68c06800-6fc2-11ea-8238-08d43a37dc1d.jpg" width="200" height="204"></td>
<td><img src="https://user-images.githubusercontent.com/16888339/77706334-652ce100-6fc2-11ea-9c5a-4dba1e7ef7cd.jpg" width="200" height="204"></td>
</tr>
</table>
This branch does two things:
1. Allows the user to add custom words to the language the current layout belongs to. The current layout  language always appears first  in the list now.
2. Adds a new checkbox in language settings, right after `Quick fixes and abbreviations`. It's unchecked by default. When checked, it disables autotext to every language checked in `Override default dictionary` except the …

put current layout language first in the dictionary overriding list

---

ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_minimal.xml
ime/app/src/main/res/xml/ext_kbd_top_row_nav_alt_no_numb.xml
ime/app/src/main/res/xml/extension_keyboards.xml
ime/app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

This PR adds a new variant of the `Navigation keys alternative` top row with no numbers row on password mode. This is to make it compatible with the  the new coming PR: [2207](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2207)
It also removes emoji on long press on the space bar for the `Minimal` generic bottom row as this bottom row already has an emoji key.

Generic rows 2

---

ime/app/src/main/res/xml/extension_keyboards.xml

…pe_top_row on a couple of generic top rows
`extensionKeyboardType` was set to `2`. I fixed that.

Changed extensionKeyboardType field on some generic top rows

---

addons/languages/german/pack/src/main/res/values-de/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_dvorak_compact.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

Hello,
I tweaked this nice English Dvorak-Compact layout into a German Layout.
Unfortunately, I am not a developer, so I apologise for my mistakes upfront. 
I am more a power user and tried my best at "copy&paste" :)
All what I did was:
-copy En Dv Compact to the german addons folder with an unique name,
-update german_keyboards.xml
-update lists with strings
Would it be possible to merge this, as it is, in the master branch?
Feedback appreciated!

German Dvorak Compact Layout

---

addons/languages/bulgarian/apk/src/main/play/listings/en-US/full-description.txt
addons/languages/bulgarian/pack/src/main/res/values/bulgarian_pack_strings_dont_translate.xml
addons/languages/bulgarian/pack/src/main/res/xml/bekl.xml
addons/languages/bulgarian/pack/src/main/res/xml/bulgarian_keyboards.xml

An enhanced variant of the Bulgarian BDS keyboard, proposed in May 2020 by a group of more than 500 linguists, teachers, writers, translators, IT specialists, professors and many more.

Include Bulgarian (enhanced) keyboard, proposed by group of 500 people in May 2020.

---

ime/app/src/main/resources/jacoco-agent.properties

The text in the commit is all I know. I'm not really all that familiar with Jacoco.
It's a problem I only found lately and seems to be caused by an upgrade in Jacoco. While I was typing, AnySoftKeyboard would randomly stop responding, but stay painted on the screen for 10 or 15 seconds (blocking the lower half of the screen), then close itself. Opening a logcat always showed the same error:
```
java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
```
(I neglected to save the rest of the logcat.)
I looked online for possible fixes to this problem and this solution seems to work, at least in my device. The file `jacoco.exec` is written in the same folder configuration files are exported to.

Avoid "jacoco.exec: open failed: EROFS (Read-only file system)

---

ime/app/src/main/res/xml-v22/quick_text_keys.xml
ime/app/src/main/res/xml-v24/quick_text_keys.xml

In smileys categories, there was the same twice. 
This is now fixed.
Explanation picture:

Removed duplicate smiley categories

---

ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGimmicksTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java

This implements part of #1682 that is about removing trailing spaces before actually removing a word.
The intended effect:
```
Before: "test this, " -> "test this," -> "test this" -> "test "
After:  "test this, " -> "test this" -> "test "
```
This actually makes the code respect the example that is already specified in the comment in the current code on line 928, this one:
> // 2b) "test this, " -> "test this"
What do you think?

Make backword remove trailing spaces

---

gradle/root_all_projects_ext.gradle

So far, I'm able to run the app on API 29 and above without any crashes from the screens that I visited. Let me know if there' are specific things I need to check for this dump that I'm not aware of.
Here are sample screenshots of my tests so far.
| Screenshots 1 | Screenshots 2|
| ------ | ----- |
| <img src="https://user-images.githubusercontent.com/73175/97093019-1410c880-1649-11eb-99c3-c56bf2893bdf.gif" width="280" /> | <img src="https://user-images.githubusercontent.com/73175/97093032-27239880-1649-11eb-8edd-ce6cecb2f502.gif" width="280" /> |
| Screenshots 3 | Screenshots 4 |
| <img src="https://user-images.githubusercontent.com/73175/97093140-ccd70780-1649-11eb-8450-39a552b12904.gif" width="280" /> | <img src="https://user-images.githubusercontent.com/73175/97093340-50ddbf00-164b-11e …

Bump compile and target SDKs to 29

---

addons/languages/german/pack/src/main/res/xml/de_adnw.xml
addons/languages/german/pack/src/main/res/xml/de_dvorak_compact.xml
addons/languages/german/pack/src/main/res/xml/de_neo2.xml
addons/languages/german/pack/src/main/res/xml/de_neo2_simple.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_broad.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_extra.xml
addons/languages/german/pack/src/main/res/xml/de_qwerty_slim.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz_broad.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz_extra.xml

I added the Long-S (ſ, U+017F) to all German keyboards as popup on s . This is very useful for people trying to distinguish Long-S from Round-S in old(-style) texts and communication. For all other people it should at least do no harm :) 
<del>P.S. I have no running build environment. "But what could possibly go wrong."<del>
[addons-languages-german-apk-1.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/5471239/addons-languages-german-apk-1.zip)
CC: @xoomerq @nicoursi @chrbauer @thomaseizinger ; as all of you have edited the German pack.

add Long-S (ſ, U+017F) to all german keyboards

---

addons/languages/italian/pack/src/main/res/xml/italian_qwerty_with_symbols.xml

Also done [here](https://github.com/rkkr/simple-keyboard/pull/214) and [here](https://github.com/dslul/openboard/pull/241).
A non-disruptive yet useful introduction for the communities using the schwa in [Italy](https://it.wikipedia.org/wiki/Scev%C3%A0#In_Italia) and in Italian. (several sources: [[0](https://globalvoices.org/2020/09/11/are-romance-languages-becoming-more-gender-neutral/)][[1](https://thesubmarine.it/2020/08/03/schwa-linguaggio-inclusivo-vera-gheno/)][[2](https://asteriscoedizioni.com/prodotto/il-corpo-del-testo-elementi-di-traduzione-transfemminista-queer-uscita-9-dicembre/)][[3](https://www.effequ.it/femminili-singolari/)][[4](https://www.valigiablu.it/linguaggio-inclusivo-dibattito/)][[5](https://jacobinitalia.it/linvidia-dellasterisco/)], also compare …

add "ə" to Italian layout

---

addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_adnw_koy.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

This PR contains the KOY-variant of the AdNW layout (w/ some minor changes, see below) in the German language pack.
For ease of use, I used an ortholinear layout like some ergonomic keyboards do and rearranged one key. Furthermore, I moved the shift keys to the bottom row, sacrificing the up/down arrows. This way, broader keys (9% vs. 8%) are possible. I found this alternative to be a rather minor change compared to the normal key alignment of AdNW in ASK but being much more usable.
If you wish, I can also add a layout with the default arrangement. And in general, just let me know, if you'd like to see something changed in order to make the PR more adequate to merge, @menny .

add KOY variant of AdNW to German language pack

---

addons/languages/english/pack/src/main/res/values/english_pack_strings.xml
addons/languages/english/pack/src/main/res/values/english_pack_strings_dont_translate.xml
addons/languages/english/pack/src/main/res/xml/english_keyboards.xml
addons/languages/english/pack/src/main/res/xml/qwertz_symbols.xml
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSubtypeTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardAddOnTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardFactoryTest.java

Added an English QWERTZ keyboard with symbols as popups, very similar to the Gboard layout. In the German comments on PlayStore some were complaining that there is no WERTZ keyboard for English language. 
By the way: do you need someone who responds to these comments in German? Some people complain about stuff which could be changed in the settings. They couldn't find it or haven't even had a look the settings..

Added an English QWERTZ keyboard

---

addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz_symbols.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

What was definitely missing for me was a keyboard which is similar to the one from Gboard - from where i switched recently. So I added this one.
Here is how it looks: 
And here for comparison the Gboard:

Added a german keyboard with symbols

---

addons/languages/portuguese/pack/src/main/res/xml/qwerty_with_symbols.xml

The ordinals ("first" can be written as "1º" or "1ª" depending on gender) are in very common use in Portuguese, even having a dedicated key on Portuguese keyboards.
In software keyboards they are usually implemented as alternative symbols to A and O.
This was the only file i found where these changes made sense.
This is a proposed fix to #2252

fix to #2252 added fe/male ordinals to pt keyboard

---

addons/languages/english/pack/src/main/res/values/english_pack_strings.xml
addons/languages/english/pack/src/main/res/xml/dvorak_with_symbols.xml
addons/languages/english/pack/src/main/res/xml/english_keyboards.xml
addons/languages/english/pack/src/main/res/xml/popup_dvorak_with_symbols_h.xml
addons/languages/english/pack/src/main/res/xml/popup_dvorak_with_symbols_i.xml
addons/languages/english/pack/src/main/res/xml/popup_dvorak_with_symbols_t.xml
ime/app/src/main/res/values-es/strings.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_minimal_less_punctuation.xml
ime/app/src/main/res/xml/extension_keyboards.xml
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSubtypeTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardAddOnTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardFactoryTest.java

This pull request adds an English Dvorak layout with common symbols above the keys, similar to the existing QWERTY with symbols layout. It also adds a bottom row variant without the "." and "," keys, which are redundant when using Dvorak. This partially addresses the concerns in #1667.

Improve English Dvorak usability

---

addons/languages/romanian/pack/src/main/res/xml/romanian_qwerty.xml

The Romanian diacritics [șțăâî](https://en.wikipedia.org/wiki/Romanian_alphabet#Special_letters) weren't given priority in the Romanian keyboard so I shifted them to the first position under their respective letters.

Moved Romanian diacritics up in pop-ups.

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java

There is currently an issue with the way ASK handles word selection during gesture typing such that if the user selects an option from the suggestions bar after swiping a word, ASK will internally select the suggestion _again_ when the user begins swiping the next word. This change ensures that pickSuggestionManually will only be called once per word during gesture typing.
This fixes #2817 and #2846, but does not fix #2813 or #2841. I believe those are (at least partly) separate issues.

Fix double call to pickSuggestionManually when swiping after correction

---

ime/app/src/main/res/xml/popup_kaomoji.xml

I didn't change any of the lines that were in there, so those kaomoji still end in `\u0020`. I'm not sure why that's there. I couldn't add it similarly to the new additions without it appearing as part of the kaomoji during local testing. Definitely something that someone more familiar with the code should look at. Maybe I'm missing something and it does need to be added.
Responds to issue #3031 .

categorized and added more kaomoji

---

ime/app/src/main/res/values/settings_keys_dont_translate.xml

Adding Sardinian ("sc") to the list of languages for the "force locale" setting.

Adding Sardinian to the "force locale" setting list

---

gradle.properties
gradle/root_all_projects_ext.gradle

Fixes opening ASK settings from launcher on master in release build.
https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0
Relevant bug fix (since 2.4.0-alpha04):
> Add ProGuard rules for @Navigator.Name, fixing issues when using R8 3.1 full mode.
See https://issuetracker.google.com/issues/191654433
Also remove deprecated options from gradle.properties.

Bump AndroidX Navigation 2.4.0

---

addons/languages/spain/pack/src/main/res/xml/es_qwerty.xml
addons/languages/spain/pack/src/main/res/xml/es_qwerty_with_symbols.xml
addons/languages/spain/pack/src/main/res/xml/es_qwerty_with_symbols_alt.xml

See https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2915.
In Spanish, graphic accents ("[acentos gráficos](https://es.wikipedia.org/wiki/Acento_gr%C3%A1fico)" or "tildes") are extremely common. These accents appear only on the vowels (áéíóú). Right now, the default popup keys for these letters on long-press are numbers, which makes it cumbersome to add accents.
This PR prioritizes accents over numbers on the letters "aeiou", since (at least in Spanish) it is more common to long-press to add an accent than to add a number (plus generally there are more suitable options to add numbers: number row, symbols/numeric keyboard).

Spanish: prioritize accents over numbers in popups

---

addons/languages/english/pack/src/main/res/xml/qwerty.xml

The letter 'ň' was missing from letter 'n' popup on the English QWERTY Latin keyboard

Add letter ň to letter n popup on English QWERTY Latin keyboard

---

addons/languages/persian/pack/src/main/res/xml/persian_qwerty.xml
addons/languages/persian/pack/src/main/res/xml/persian_qwerty_compact.xml
addons/languages/persian/pack/src/main/res/xml/popup_qwerty_space.xml

Add [Left-To-Right Embedding](https://unicode-table.com/en/202A/), [Right-To-Left Embedding](https://unicode-table.com/en/202B/) and [Pop Directional Formatting](https://unicode-table.com/en/202C/) as popup characters on space key for writing English text in Persian paragraphs and Persian text in English paragraphs with proper bidi formatting.

add embedding RTL, LTR and PDF for bidi support

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java

With auto-capitalise off, the shift key would disengage when
gesture-typing and the word would be full lowercase. This ensures that
if shift is active when the gesture starts, then the word will be
shifted.

Gesture typing respects the initial state of the shift key

---

.github/workflows/checks.yml
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/main/res/layout/clear_gesture_action.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardQuickTextTest.java

Similar to Gboard, pressing backspace immediately after gesture input
will clear the word you gestured.
Good for correcting mistaken gesture input.
Marked draft since I haven't been able to run the tests yet

Backspace after gesture clears word

---

ime/app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSupport.java

When running aapt on keyboard XML files, it allows android:keyHeight to be a dimension or fraction as well as a reference to one of the height codes. Previously, values like "20dp" or "10%p" were ignored and replaced with the default key height. This commit allows layouts to specify precise dimensions if desired.

Handle keyHeight if given as dimension/fraction

---

addons/languages/german/pack/src/main/res/xml/de_qwerty_slim.xml

Goes from this:
to this:
Notice the backspace key.

Fixed short backspace on the German QWERTY slim layout

---

ime/fileprovider/src/main/java/com/anysoftkeyboard/fileprovider/LocalProxy.java
ime/fileprovider/src/test/java/com/anysoftkeyboard/fileprovider/LocalProxyTest.java

When we proxy we lose the MIME type information, so set the file extension based on the MIME type so that contentResolver.getType() will still work on the new URI, this fixes image preview in the text box etc.
Fixes #3542

Fix MIME type for media insertion

---

build.gradle

Seems to be unrelayable. Hopefully we can get without it.

removing jitpack.io

---

addons/languages/english/pack/src/main/res/xml/qwerty_with_symbols.xml

this would add the ŷ (y with ^ diacritic) symbol to the english qwerty with symbols keyboard, when you long press y, added at the end of the popup options because they appear to be arranged in UTF8 symbol order and ŷ comes after the other current popup options

add ŷ to popup

---

README.md

The image was missing and only the alt text got displayed. I changed the URL according to [F-Droid](https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md).
E.g.:
```html
<a href="https://f-droid.org/packages/YOUR.APP.ID">
alt="Get it on F-Droid"
height="80">
</a>
```

Fix link to missing "Get it on F-Droid" image in README.md

---

buildSrc/src/main/java/MergeWordsListTask.java

This fix addresses a build-time error for the recent build [https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/498dab3a1cba1b197b7b48aea40e7e595c50d299] in which generating an english word list fails on Windows due to inappropriate heuristic matching for the word list build directory (relies on searching for '/build/' in the folder path to avoid checking itself against duplicate words; added another condition for the alternate filesep).
(sorry... here's try 3.)

Fix build folder search heuristic for duplicate word finding

---

CONTRIBUTING.md

Very minor issue, but the code of conduct was linked improperly in CONTRIBUTING.md.

Fix Code of Conduct link in CONTRIBUTING.md

---

addons/languages/english/pack/src/main/res/xml/qwerty.xml

Added ǎ and ǐ, which more or less completes the ability to type [pinyin](https://en.wikipedia.org/wiki/Pinyin) in the QWERTY keyboard (not counting ü-tones). The vowels+tones used in pinyin are:
```
āáǎàa
ēéěèe
īíǐìi
ōóǒòo
ūúǔùu
ǖǘǚǜü
```
(However, the `ü` can also be written as a `u` (with no umlaut) or v or even yu depending on context and style.)
Before this pull request, the ability to type in pinyin is nearly complete on AnySoft keyboard in QWERTY except for just two tones that are missing.  It seems like an important and low-hanging fruit to round off the ability to write in pinyin. Chinese is the second most widely spoken language in the world, after all.

Add ǐ and ǎ to qwerty, to complete pinyin

---

ime/voiceime/src/main/java/com/google/android/voiceime/ActivityHelper.java

Currently, AnySoftKeyboard shows a voice recognition result dialog even if there's only one result. I assume this dialog is intended to allow picking between multiple results, but when there's only one result, it just adds an unnecessary step. This change shows the dialog only when there's two or more results, and skips to typing the text instantly if there's only one.
Example of the dialog with only one result:

Don't show voice result dialog when only 1 result

---

ime/voiceime/build.gradle
ime/voiceime/src/main/java/com/google/android/voiceime/ImeTrigger.java
ime/voiceime/src/main/java/com/google/android/voiceime/VoiceRecognitionTrigger.java
ime/voiceime/src/test/java/com/google/android/voiceime/VoiceRecognitionTriggerTest.java

Currently, ImeTrigger is hardcoded to only look for voice IME subtypes whose package names are prefixed with `com.google.android`. This means that only Google Voice Input is allowed to be picked by ImeTrigger.
From my understanding, it's adequate to check that the subtype equals `"voice"`. Any input method subtype advertising its mode as `"voice"` is probably capable of doing voice input. So I'm not certain why this check was there in the first place, other than to prioritize Google's Voice Input on the belief that Google's probably works better than whatever else is installed by the user or vendor.
This PR removes this check to allow non-Google voice inputs to be picked by ImeTrigger. Previously it was still possible for third party voice inputs to be picked by IntentApiTrigger instead, …

Fix hardcoded google voice input check

---

ime/app/src/main/res/values/styles_yochees_keyboard_theme.xml

This isn't the "correct" way to fix this, which would be creating a separate set of icons for the yochees light theme, but it fixes #2439 and since no-one touched that bug in 3 years, I think this is good enough.

Temporary fix for Yochees Light theme having unreadable icons

---

addons/languages/hebrew/pack/src/main/res/xml/heb_qwerty_niqquds.xml

This symbol is used extremely often in many abbreviations (e.g. words for kilogram, doctor etc.) and typing Geresh twice is not a proper substitute.
The change wasn't tested as I have no dev environment set up.

Add Gershayim to Hebrew

---

addons/languages/kachin/pack/src/main/res/xml/dvorak.xml

Eth & thorn, ð & þ, were historic letters to English & still common in Icelandic words. There seems to be recurring movements online to use them in English today too to supplant the most common digraph, “th”, for [θ] [ð] sounds.
Placement was at the beginning of the list as these characters have higher codepoint values than the others (altho the order doesn’t have an order I personally understand—and ideally users could reorder them).

en dvorak: add ð & þ

---

gradle/root_all_projects_ext.gradle

This will be needed until we bump the minSdk value.

A workaround to allow building on an aarch64 machine

---

ime/dictionaries/jnidictionaryv2/src/main/jni/include/dictionary.h
ime/dictionaries/jnidictionaryv2/src/main/jni/source/com_anysoftkeyboard_dictionaries_ResourceBinaryDictionary.cpp
ime/dictionaries/jnidictionaryv2/src/main/jni/source/dictionary.cpp

The breaking-words feature is failing when typed words are getting the same freq everytime. Instead, we now ALWAYS return the typed word as the first word in the list, and always with the actual freq.

Fix typed-word freq

---

addons/languages/greek/pack/src/main/res/values/greek_strings.xml
addons/languages/greek/pack/src/main/res/xml/greek_keyboards.xml
addons/languages/greek/pack/src/main/res/xml/greek_qwerty.xml
addons/languages/greek/pack/src/main/res/xml/greek_qwerty_polytonic.xml

I wanted a better way to type in Polytonic Greek. [Apptide](https://ancient-languages-pack-for-anysoftkeyboard.en.aptoide.com/app) has an ancient languages pack that supports Polytonic Greek, but it is hard to use because of the large popup menus. So I have created one that uses combining diacritics. and lists them in a row for easy access. now there is some difficulty because a lot of systems including mine(android 15) do fine if one types: Vowel, Breathing Mark, Tonos(ἔ); but have trouble if one types: Vowel, Tonos Breathing Mark, (έ̓). but I know not how to solve this problem in AnySoftKeyboard. I don't think I did anything "Copyright-able" so do with this keyboard as you please. I do not know whether it really belongs in the Greek package or in a new package for itself.

added Polytonic Greek Keyboard

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardRxPrefs.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardForceLocaleTest.java
js/contributors/contributors.ts
js/localization_tools/locales_generator.test.ts
js/localization_tools/locales_generator.ts

This commit addresses several issues related to locale handling:
1.  **Locale Generation (`js/localization_tools/locales_generator.ts`):**
*   Adds "System" as the first entry in the generated `settings_key_force_locale_values` string-array.
*   Includes generic locales (e.g., "en" for "en-US") in the array. If a direct generic translation (e.g., `values-en`) exists, it's used; otherwise, the generic version is derived from specific locales (e.g., "en" from `values-en-rUS`).
*   Ensures the final list is unique and sorted alphabetically after "System".
*   Unit tests for `locales_generator.ts` have been updated to reflect these changes, verifying the "System" entry, generic locale inclusion, and correct sorting.
2.  **Android System Locale Handling (`AnySoftKeyboardRxPrefs.java`):**
* …

Fix: Update locale generation and System locale handling

---

ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardDictionaryEnablingTest.java

- Set 'Try splitting words for correction' to be off by default.
- Add '[beta]' prefix to the title of the 'Try splitting words for correction' setting to indicate its experimental status.

feat: Change word splitting default and update title to beta

---

.github/workflows/deployment_promote.yml

This change adds the release-branch-ime-v1.12-r1 branch to the list of releasable branches in the deployment_promote.yml workflow.

Add release-branch-ime-v1.12-r1 to deployment workflow

---

ime/app/src/main/play/release-notes/en-US/alpha.txt
ime/releaseinfo/src/main/java/com/anysoftkeyboard/releaseinfo/VersionChangeLogs.java

This commit resets the content of the alpha release notes file (ime/app/src/main/play/release-notes/en-US/alpha.txt) with a placeholder message for the upcoming version 1.13. It also includes the link to the new milestone.

Reset alpha release notes for 1.13

---

.github/workflows/checks.yml
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardColorizeNavBar.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/EffectsSettingsFragment.java
ime/app/src/main/res/values-v36/settings_defaults_dont_translate.xml
ime/prefs/src/main/java/com/anysoftkeyboard/prefs/RxSharedPrefs.java
ime/prefs/src/test/java/com/anysoftkeyboard/prefs/RxSharedPrefsTest.java

fixes #4266
For API level 36 and above, the navigation bar colorization should always be enabled. This commit introduces a resource override to enforce this behavior.
Also, a preference upgrade step was added to ensure that existing installations are also updated.
The UI setting is hidden for API 36+ since it can no longer be changed.
Finally, the `AnySoftKeyboardColorizeNavBar` class is updated to ensure the feature is always on for API 36+.

Fix nav-bar colorization setting for API 36
