README.md

Please, also update the releases on F-Droid

Added get it on F-Droid

---

app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
app/src/main/res/xml/ext_kbd_bottom_row_alt_with_mic.xml
app/src/test/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboardRowsTest.java

unless specifically requested not to. Issue #739

making sure there is alway a bottom row

---

app/src/main/java/com/anysoftkeyboard/keyboards/GenericKeyboard.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardKeyboardSwitchingTest.java
app/src/test/java/com/anysoftkeyboard/keyboards/GenericKeyboardTest.java
circle.yml

change PASSWORD mode to NORMAL for symbols keyboards

---

app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithQuickText.java
app/src/main/java/com/anysoftkeyboard/quicktextkeys/ui/QuickTextPagerView.java
app/src/test/java/com/anysoftkeyboard/quicktextkeys/ui/QuickKeysKeyboardPagerAdapterTest.java
app/src/test/java/com/anysoftkeyboard/quicktextkeys/ui/QuickTextPagerViewTest.java

Fixing issue with background in QuickText

---

app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/colemak.xml
app/src/main/res/xml/dvorak.xml
app/src/main/res/xml/keyboards.xml
app/src/main/res/xml/popup_16keys_ghi.xml
app/src/main/res/xml/popup_16keys_jkl.xml
app/src/main/res/xml/qwerty_compact.xml
app/src/main/res/xml/terminal.xml
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardKeyboardSubtypeTest.java
app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardAddOnTest.java

Closes #579,  #422, #748, #902, #966

Importing AlternativeEnglishLayouts (Colemak, Dvorak, compact) and SSH/Terminal

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/ext_kbd_bottom_row_old.xml
app/src/main/res/xml/extension_keyboards.xml
app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

Add Old School keyboard bottom extension 

---

circle.yml
scripts/ci_setup.sh

This will complete:
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1017
https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1016

Introducing Circle CI workflows

---

app/build.gradle
scripts/ci_deploy.sh

Will implement https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1002

update to Google App Signing

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java
app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java
app/src/main/java/com/anysoftkeyboard/dictionaries/UserDictionary.java
app/src/main/java/com/anysoftkeyboard/dictionaries/content/ContactsDictionary.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
app/src/main/java/com/anysoftkeyboard/ime/InputViewBinder.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java
app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java
app/src/main/play/en-US/whatsnew
app/src/main/res/values/strings.xml
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardTest.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardViewRelatedTest.java
app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestTest.java
app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestionsProviderTest.java
app/src/test/java/com/anysoftkeyboard/nextword/NextWordDictionaryTest.java
nextword/src/main/java/com/anysoftkeyboard/nextword/NextWordDictionary.java
nextword/src/main/java/com/anysoftkeyboard/nextword/NextWordGetter.java
nextword/src/main/java/com/anysoftkeyboard/nextword/NextWordSuggestions.java

Will not learn new words in Incognito mode.
Long-press ENTER to show settings, and pick Incognito Mode

Incognito Mode. Issue #994

---

app/src/main/res/values/strings.xml

supersedes https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/629 and fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/628

 Made reference to app store independent of Google

---

README.md
app/src/main/res/xml/dvorak.xml

Closing https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1045

Adding bountysource and Dvorak popup chars

---

app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetector.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java

1. first time not drawing path when gesture typing.
2. should not draw on the non-alphabet keyboard.

Fixed bugs

---

app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingPathDrawHelper.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java

I've made a tail effect for gesture typing path just like below:

modify gesture drawing type to tail-effect

---

app/src/debug/res/xml/keyboard_with_false_show_preview_at_root.xml
app/src/debug/res/xml/keyboard_with_no_show_preview_at_root.xml
app/src/debug/res/xml/keyboard_with_true_show_preview_at_root.xml
app/src/main/java/com/anysoftkeyboard/addons/AddOn.java
app/src/main/java/com/anysoftkeyboard/keyboards/GenericKeyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSwitcher.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java
app/src/main/res/xml-sw600dp/simple_datetime.xml
app/src/main/res/xml-sw600dp/simple_numbers.xml
app/src/main/res/xml-sw600dp/simple_phone.xml
app/src/main/res/xml/simple_alt_numbers.xml
app/src/main/res/xml/simple_datetime.xml
app/src/main/res/xml/simple_numbers.xml
app/src/main/res/xml/simple_phone.xml
app/src/main/res/xml/symbols_alt.xml
app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
app/src/test/java/com/anysoftkeyboard/keyboards/GenericKeyboardTest.java
build.gradle
gradle/root_general.gradle

Also, bumping plugin and ASK-API version

Allow overriding showPreview at root level

---

app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/ext_kbd_bottom_row_simple.xml
app/src/main/res/xml/ext_kbd_top_row_numbers_simple.xml
app/src/main/res/xml/extension_keyboards.xml
app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

I added simple style for bottom and top row. It is based on ext_kbd_top_row_numbers and ext_kbd_bottom_row_alt.
I just removed unused symbols from ext_kbd_top_row_numbers. 
Also I removed smile and added characters selection button to ext_kbd_bottom_row_alt and some symbols. That's it.

Added top and bottom row style

---

app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
app/src/main/res/values/styles_plain_dark_keyboard_theme.xml

Now if hintText is too long it is replaced with dots. I think we need to show substring of that text. 
Better to see something than nothing, right?

HintText contains substring if it's too long.

---

circle.yml
scripts/ci_deploy.sh

Reverts AnySoftKeyboard/AnySoftKeyboard#1208

Revert "Release Canary also after RELEASE"

---

app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java
base-rx/build.gradle
build.gradle

adding some logs to tackle a crash in beta

---

dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/Dictionary.java
dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/DictionaryBackgroundLoader.java
jnidictionaryv2/src/main/java/com/anysoftkeyboard/dictionaries/jni/ResourceBinaryDictionary.java
jnidictionaryv2/src/main/jni/source/com_anysoftkeyboard_dictionaries_ResourceBinaryDictionary.cpp

It seems that close is called multiple times and native gets confused

A possible fix for native dict crash

---

app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java
app/src/main/play/en-US/whatsnew
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sc/strings.xml
app/src/main/res/values-uk/strings.xml

And merging release-branch r3 into _master_

Start work on 1.9- r4

---

gradle/dictionary_generator.gradle

It must run after :app:clean, and any build task of app must run after it.

Ensure correct dependencies around make-dictionary

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardDictionaryGetWordsTest.java

Fix revert-committed-text when auto-space is disabled.

---

app/src/main/res/values-uk/currency_data.xml

Create currency_data.xml for uk

---

README.md
app/src/main/res/values/strings.xml
app/src/main/res/xml/keyboards.xml
app/src/main/res/xml/workman.xml
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardKeyboardSubtypeTest.java
app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardAddOnTest.java
app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardFactoryTest.java

Adds the [Workman](https://workmanlayout.org/) layout as an English alternative.
Closes #1440

Add Workman alternative English layout

---

app/src/main/res/xml/colemak.xml
app/src/main/res/xml/workman.xml

I fixed a minor spacing issue with the shift and backspace keys. Then I added punctuation keys to the popup characters, and gave them hintlabels.
I'm still confused about how to update the changelog but I think all my contributions this week can be boiled down to 3 main bullet points:
* Added Workman English layout.
* Added Terminal common top row, for using terminal keys with any layout.
* Added more long press characters to the Colemak layout.

More Colemak & Workman Improvements

---

base-rx/build.gradle
base-rx/src/main/java/com/anysoftkeyboard/rx/RxSchedulers.java

https://medium.com/@sweers/rxandroids-new-async-api-4ab5b3ad3e93

Bumping RX and using async UI scheduler

---

app/src/main/res/values/styles.xml

overriding the default, which is Large. Fixes issue #1496

Setting preferences title as Normal.Bold

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardIncognito.java
app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java
app/src/main/play/release-notes/en-US/alpha.txt
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGimmicksTest.java
app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardViewRelatedTest.java
app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
circle.yml

The keyboard will support the ime_incognito_flag and automaticly enable and disable the incognito mode if requested by the app (e.g. private modes in FF or Chrome).

Support for IME Incognito Flag

---

app/build.gradle
app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java

https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1555

This release is 1.10

---

app/src/main/java/com/anysoftkeyboard/utils/LocaleTools.java

This is instead of https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1597

Updating config to reflect OS locale

---

app/src/main/res/menu/add_on_selector_menu.xml

Making keyboard theme configurations button visible.
Issue https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1627

Making keyboard theme configurations button visible.

---

app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
app/src/test/java/com/anysoftkeyboard/ViewTestUtils.java
app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewTest.java

Ensuring gesture-typing is not done with more than one finger

---

app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetector.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
app/src/main/res/values/dimens.xml

This pull request greatly improves the speed+quality of gesture typing, at least for me!
In particular:
- **Faster path generation**: From 12s to 3.5s (English, debug mode), from 17s to 3s (German, debug mode)
- **Faster candidate finding**: From 120ms to 80ms when typing "implementation" on an English Keyboard (in debug mode)
- **Better special character handling**: Previously, when a keyboard had two keys with the same base character (e.g., "ä" and "a" on the German keyboard), the path generation would always choose the base character, making it nearly impossible to gesture type words like "Männer". This now works properly.
- Most importantly: **Much better word recognition**: At least for me, the recognition of the gesture typed words is much better, especially for long words. For …

Gesture typing improvements

---

app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java
app/src/main/java/com/anysoftkeyboard/dictionaries/sqlite/AutoDictionary.java
app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
app/src/main/res/xml/ext_kbd_bottom_row_iphone.xml
app/src/main/res/xml/ext_kbd_bottom_row_iphone_with_mic.xml
app/src/main/res/xml/ext_kbd_bottom_row_ng.xml
app/src/main/res/xml/ext_kbd_bottom_row_old.xml
app/src/main/res/xml/ext_kbd_bottom_row_regular.xml
app/src/main/res/xml/ext_kbd_bottom_row_regular_with_voice.xml
app/src/main/res/xml/ext_kbd_top_row_terminal.xml
app/src/main/res/xml/popup_one_row.xml
app/src/main/res/xml/popup_three_rows.xml
app/src/main/res/xml/popup_two_rows.xml
app/src/main/res/xml/quick_text_list_popup.xml
app/src/main/res/xml/simple_datetime.xml
app/src/main/res/xml/simple_numbers.xml
app/src/main/res/xml/simple_phone.xml
app/src/main/res/xml/symbols.xml
app/src/main/res/xml/symbols_16keys.xml
app/src/main/res/xml/symbols_alt.xml
app/src/main/res/xml/symbols_alt_16keys.xml
scripts/adb.sh

These commits fix small but basic bugs. Two of them are caused by my previous code... sorry :sweat_smile: 
- Dictionary auto-learning, which was supposed to be fixed with #1887, wasn't correctly fixed. Details are given in the summary for commit 8159890377c75a89d841aec62bfd93bc214dffa9.
- #620 is fixed with commit 60e6e42f73d16be59eafdb9766c5dc5bec6e773a, but please check the summary; in doing so, I removed a part of code added by @menny in e041360c5f2ebb9bf0c4663cd4e38cf1cf93e83a. **This doesn't seem to break anything but please double-check.**
- After fixing dictionary auto-learning, I wrote a quick fix for #1810 which appears to work, even after reboot. The preference `settings_key_use_user_dictionary` wasn't actually connected to anything.
- Your backword function (is that supposed to …

Bug fixes for #620, #1810; corrections for #1887, #1636.

---

.github/actions/codecov/action.yml
.github/actions/codecov/codecov.yml
.github/workflows/checks.yml
gradle.properties

It wasn't the issue with missing check-suite events

Re-adding codecov

---

.github/actions/codecov/action.yml
.github/actions/collect-reports/action.yml
.github/actions/deploy-request/action.yml
.github/actions/deploy-status/action.yml
.github/actions/deploy/action.yml
.github/actions/test-shard-run/action.yml
.github/workflows/checks.yml
.github/workflows/deploy.yml
.github/workflows/packs_md_update.yml

See: https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md\#using-in-an-alpine-linux-container

Install required bins for create-pull-request action

---

app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java

Hi, I'm Emanuele Iannone, a master student at University of Salerno.
Since my bachelor's thesis I have been working on a **code smell refactoring plugin** called *aDoctor*, which is able to identify and fix energy-related problems in Android apps.
I launched it on your project, finding different instances of code smells. I chose one of them and let the plugin automatically fix it.
In this case I chose Member Ignoring Method, that is present when a non static method does not use at all instance variables and other non static methods. These kind of smell may have a non trivial impact on energy consumption, as shown in this paper: `https://www.sciencedirect.com/science/article/pii/S0950584918301678`.
Besides, this kind of refactoring does not impact on the functionalities of your app, so it …

Refactor Member Ignoring Method smell in SuggestionsProvider class

---

addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_adnw.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

Layout "Aus der Neo Welt" added

---

ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
ime/app/src/test/java/com/anysoftkeyboard/ViewTestUtils.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewTest.java

And also, refactor UI utils for multi-finger simulation

Fix gesture-with-two-fingers issue

---

addons/languages/tamazight/pack/src/main/res/xml/tamazight_autotext_kab.xml
addons/languages/tamazight/pack/src/main/res/xml/tamazight_taqbaylit_azerty.xml

Hi,
Introducing some corrections in kabyle/Tamazight layout after we discussed some issues with some kabyle FLOSS translators.

Corrections in kabyle

---

addons/languages/spain/apk/src/main/play/release-notes/en-US/alpha.txt
addons/languages/spain/pack/src/main/res/values/spanish_strings.xml
addons/languages/spain/pack/src/main/res/xml/es_qwerty_with_symbols.xml
addons/languages/spain/pack/src/main/res/xml/es_qwerty_with_symbols_alt.xml
addons/languages/spain/pack/src/main/res/xml/spanish_keyboards.xml
ime/app/src/main/res/xml-es/popup_domains.xml

Created two new spanish layouts with symbols.

Spanish layouts

---

ime/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java

This fixes #2130 
It looks like it's working correctly now. The devs can have a look at this little piece of code, in case I missed some behaviour.

Auto capitalize autotext if typed word is capitalized

---

ime/app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestionsProviderTest.java

I realized that this unit test was really not testing much ;) I think it's better now.

Fixed unit-test

---

addons/languages/kurdish/pack/src/main/res/xml/kurmanji_qwerty.xml

Added Kurmanji vowel words ( î, ş, ç, û, ê )
Screenshot:
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/sg42j0Rf/IMG-20200309-025719-1.jpg' border='0' alt='IMG-20200309-025719-1'/></a>

Kurdî(Kurmanji) Qwerty Standard Layout

---

addons/languages/persian/pack/src/main/res/values/strings.xml

there is a person name on the layout. i just removed it.

Update sting.xml of persian keyboard layout

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSwipeListener.java
ime/app/src/main/res/values/arrays.xml
ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGesturesTest.java

I'm trying to move to AnySoft from Minuum, which has this feature, and I can't live without it.
It works (I'm using it) but I'm not an Android dev so hopefully I've done it right.

feat: add <space> as an action for gestures

---

ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/res/values-fr/strings.xml
ime/app/src/main/res/values/arrays.xml
ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/settings_keys_dont_translate.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/prefs_keyboard_theme_tweaks.xml
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBaseTest.java

Having option to choose between small hints, normal (current), or bigger hints.

Increment size hint letters

---

addons/languages/french/pack/src/main/res/xml/azerty.xml

I improved French Azerty on hints, because some characters are not very used, like ł.

Azerty French kbd improvements on hints

---

ime/app/src/main/java/com/anysoftkeyboard/ui/settings/AbstractAddOnsBrowserFragment.java
ime/app/src/main/res/layout/add_on_browser_view_item.xml

Now, for any to long string in menus, the text will be left scrolling. 
This is to be able to read what can be in parenthesis

Added horizontal scrolling layout for view item

---

ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_ng_no_apo.xml
ime/app/src/main/res/xml/extension_keyboards.xml
ime/app/src/test/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactoryTest.java

In french azerty keyboard, there is 2 apostroph in the keyboard. And one is on the bottom row layout

Added new generation bottom row without apostroph

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboard.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardIncognito.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboardTest.java

This was in clipboard suggestion action.

Fix issue with password field detection

---

addons/languages/russian2/pack/src/main/res/xml/russian2_keyboards.xml
addons/languages/russian2/pack/src/main/res/xml/russian_english_qwerty.xml

For lovers of Russian passwords in Latin letters.

Russian/English QWERTY keyboard

---

README.md
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java
ime/app/src/main/res/xml/ext_kbd_bottom_row_alt.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_alt_with_mic.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_iphone.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_iphone_with_mic.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_ng.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_old.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_regular.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_regular_with_voice.xml
ime/app/src/main/res/xml/ext_kbd_bottom_row_simple.xml
scripts/adb.sh

The primary goal for this commit is to fix `scripts/adb.sh`, a script that's really useful for me to debugging (and one I need to recreate every time I create a new branch). I'm probably the only person using that script, but it _does_ make things easier for me.
I also ported some micro-commits which I (wrongly) put in #1921, but are actually unrelated. I don't mind delaying the merge of that PR, it's a big change (and it might have a memory leak which I'm working on), but it also delays bug fixes for very minor, very long-lived, and annoying bugs. Most of them were marked as stale and closed, but aren't actually fixed.
My last commit is another self-serving addition, but I someone else will probably find it useful.
If you find it useful to merge this PR, I'll rebase #1921 to exclude all …

Fix adb helper script; tweaks to layouts; other commits ported from #1921

---

addons/languages/italian/apk/src/main/play/release-notes/en-US/alpha.txt
addons/languages/italian/pack/src/main/res/values/italian_pack_strings.xml
addons/languages/italian/pack/src/main/res/values/italian_pack_strings_dont_translate.xml
addons/languages/italian/pack/src/main/res/xml/english_qwerty_with_numbers_row.xml
addons/languages/italian/pack/src/main/res/xml/italian_keyboards.xml
addons/languages/italian/pack/src/main/res/xml/italian_qwerty.xml
addons/languages/italian/pack/src/main/res/xml/italian_qwerty_with_symbols.xml
addons/languages/italian/pack/src/main/res/xml/italian_qwerty_with_symbols_number_row.xml

It adds a new italian layout with a number row included so that there is more space for more symbols.

new Italian layout and some modifications to italian qwerty

---

ime/app/src/main/java/com/anysoftkeyboard/prefs/GlobalPrefsBackup.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/MainFragment.java

Custom backup file selected through SAF was named "(invalid).xml" or after selected
directory's name (with a number appended), dependig on choosen content provider.
Intent.ACTION_CREATE_DOCUMENT returns directory path, so create file in it.

Create backup file in selected directory

---

ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/devicespecific/DeviceSpecificV11.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboard.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardHardware.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboard.java
ime/app/src/main/java/com/menny/android/anysoftkeyboard/SoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/TestInputConnection.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboardTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardQuickTextTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java
ime/dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/WordComposer.java

Let's hope I didn't break the entire universe.

Using less global inputs to position cursor

---

ime/base-rx/build.gradle

see https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2375

Bump RXJava, hopefully fixing a few crashes

---

addons/languages/basque/apk/build.gradle
addons/languages/danish/apk/build.gradle
addons/languages/latvian/apk/build.gradle
addons/languages/norwegian/apk/build.gradle
addons/languages/polish/apk/build.gradle
addons/quicktexts/bbcodes/apk/build.gradle

See email from [4-3732000031224]

Resubmitting apps after appeal accepted

---

addons/languages/danish/pack/src/main/res/values/danish_pack_strings_dont_translate.xml
addons/languages/danish/pack/src/main/res/xml/danish_keyboards.xml
addons/languages/danish/pack/src/main/res/xml/dvorak.xml
addons/languages/danish/pack/src/main/res/xml/qwerty.xml
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPressEffects.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSwitcher.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyboardPositionCalculator.java
ime/app/src/main/res/values-de/currency_data.xml
ime/app/src/main/res/values-el/currency_data.xml
ime/app/src/main/res/values-es/currency_data.xml
ime/app/src/main/res/values-eu/currency_data.xml
ime/app/src/main/res/values-fi/currency_data.xml
ime/app/src/main/res/values-fr/currency_data.xml
ime/app/src/main/res/values-in/currency_data.xml
ime/app/src/main/res/values-it/currency_data.xml
ime/app/src/main/res/values-iw/currency_data.xml
ime/app/src/main/res/values-ru/currency_data.xml
ime/app/src/main/res/values-uk/currency_data.xml
ime/app/src/main/res/values/currency_data.xml
ime/app/src/main/res/xml/simple_phone.xml
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardKeyboardPersistentLayoutTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyboardPositionCalculatorTest.java
scripts/adb.sh

This closes several minor issues, some of them very old. If nothing else, this should remove a couple quirks of the keyboard and shorten a little bit the issue list. (And also, add a new keyboard layout for Danish, thanks to @snkfxx.)
The greatest change is that “Reverse cycle through all keyboard” and “Cycle through all keyboards” are finally different actions, so I needed to add extra code.
Every commit is tagged with the issue it fixes.

Squash several minor bugs

---

addons/languages/persian/pack/src/main/res/xml/persian_qwerty.xml
addons/languages/persian/pack/src/main/res/xml/persian_qwerty_compact.xml

Since the bottom row is fixed due to special Persian characters, with adding the change layout button to bottom row it will be possible for users to change the top row.

Adding change layout button to bottom row 

---

CONTRIBUTING.md
addons/CONTRIBUTING.md

I've added some additional information which could definitely help some others which are not that expirienced

Added additional information to the addons/CONTRIBUTING.md

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardIncognito.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPressEffects.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewWithMiniKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyPositionCalculator.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyboardPositionCalculator.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/KeyPreviewsController.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/KeyPreviewsManager.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/NullKeyPreviewsManager.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/preview/PositionCalculator.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardBaseTest.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardPressEffectsTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyPositionCalculatorTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/preview/AboveKeyboardPositionCalculatorTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/preview/KeyPreviewsManagerTest.java

fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2630

No popups with passwords

---

gradle/checkstyle.gradle
ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardBaseTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardDictionaryGetWordsTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGimmicksTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardSelectionModificationTest.java
ime/app/src/test/java/com/anysoftkeyboard/TestInputConnection.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboardTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardQuickTextTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java

This is a possible fix for #2679

Passing delete action to WordComposer when delayed

---

ime/app/src/main/java/com/anysoftkeyboard/prefs/GlobalPrefsBackup.java
ime/app/src/main/java/com/anysoftkeyboard/ui/FileExplorerCreate.java
ime/app/src/main/java/com/anysoftkeyboard/ui/FileExplorerRestore.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/MainFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/NextWordSettingsFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/wordseditor/AbbreviationDictionaryEditorFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/wordseditor/UserDictionaryEditorFragment.java
ime/app/src/main/java/com/menny/android/anysoftkeyboard/AnyApplication.java
ime/app/src/test/java/com/anysoftkeyboard/prefs/GlobalPrefsBackupTest.java

Continuing https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2864

---

ime/app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingPathDrawHelper.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java

- enabling theming for gesture swipe typing

themeing for gesture typing

---

addons/languages/english/pack/src/main/res/xml/qwertz_symbols.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz_symbols.xml

replaces https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2740

Add a Symbol to the qwertz Keyboards

---

.github/actions/deploy/action.yml
.github/actions/deploy/deploy.sh
.github/workflows/deploy.yml
buildSrc/src/main/java/deployment/DeploymentRequestProcessStepTask.java
buildSrc/src/main/java/github/DeploymentCreate.java

We need to specify the from-track, or the plugin will promote the latest release in the Store.

Fixing play-store promotion task

---

.github/actions/deploy/deploy.sh
.github/workflows/checks.yml
.github/workflows/deploy.yml
gradle/apk_module.gradle

This is required for exposing signed APKs for users, as bundles are not easily installable

Also upload APKs when publishing

---

.github/actions/deploy/deploy.sh

we need it so we bundle not-to-be-published-packs

Revert removal of redundant bundle task

---

.github/workflows/deploy.yml

I will not want deploy to fail because of timeout...

Deploying addons is long

---

addons/languages/oldnortharabian/pack/src/main/res/xml/oldnortharabian_qwerty.xml

Please review and approve my pull request.
I made a mistake that I missed in setting the android label and codes.

Corrected wrong android codes and label

---

gradle/wrapper/gradle-wrapper.properties

See https://github.com/gradle/gradle/pull/19926 and https://github.com/Triple-T/gradle-play-publisher/issues/1037

Downgrade Gradle while waiting for fixes related to publishing

---

.github/workflows/deploy.yml
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestImpl.java
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestionsProvider.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardBaseTest.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestionsProviderTest.java
ime/app/src/test/java/com/anysoftkeyboard/dictionaries/content/ContactsDictionaryTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java

Fixes: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3227
Fixes: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2487
Fixes: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2162
Fixes: https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1933

Allowing gestures from all dictionaries

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3268

Fix unwanted revert-word after picking

---

addons/languages/german/pack/src/main/res/values-de/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/values/german_pack_strings_dont_translate.xml
addons/languages/german/pack/src/main/res/xml/de_qwertz_extended.xml
addons/languages/german/pack/src/main/res/xml/german_keyboards.xml

* added keyboard with ö,ä,ü keys but without ß

addition of new german keyboard

---

config/checkstyle/checkstyle.xml
config/checkstyle/suppressions.xml
ime/addons/src/main/java/com/anysoftkeyboard/addons/AddOnsFactory.java
ime/addons/src/test/java/com/anysoftkeyboard/addons/AddOnsFactoryTest.java
ime/app/src/main/AndroidManifest.xml
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/ExternalDictionaryFactory.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardTagsSearcher.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardRxPrefs.java
ime/app/src/main/java/com/anysoftkeyboard/keyboardextensions/KeyboardExtensionFactory.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardFactory.java
ime/app/src/main/java/com/anysoftkeyboard/prefs/GlobalPrefsBackup.java
ime/app/src/main/java/com/anysoftkeyboard/quicktextkeys/QuickTextKeyFactory.java
ime/app/src/main/java/com/anysoftkeyboard/quicktextkeys/ui/QuickTextUserPrefs.java
ime/app/src/main/java/com/anysoftkeyboard/theme/KeyboardThemeFactory.java
ime/app/src/main/java/com/anysoftkeyboard/ui/dev/DeveloperUtils.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/AbstractAddOnsBrowserFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/AdditionalUiSettingsFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/setup/WizardLanguagePackFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/setup/WizardPageBaseFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/setup/WizardPageWelcomeFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/setup/WizardPermissionsFragment.java
ime/app/src/main/java/com/anysoftkeyboard/ui/tutorials/TutorialsProvider.java
ime/app/src/main/java/com/menny/android/anysoftkeyboard/AnyApplication.java
ime/app/src/main/res/values/strings_dont_translate.xml
ime/app/src/main/res/xml/method.xml
ime/base-test/src/main/java/com/anysoftkeyboard/test/SharedPrefsHelper.java
ime/prefs/src/main/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferences.java
ime/prefs/src/test/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferencesTest.java

Attempt to:
fix https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1710
fix https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2445

Allow in lock screen

---

.github/actions/deploy/deploy.sh
.github/workflows/checks.yml
gradle/fdroid_yaml_output.gradle

This will break the building of ALL release APKs when calling generateFdroidYamls

Use finalizeBy instead of depend

---

ime/app/src/main/AndroidManifest.xml
ime/app/src/main/res/xml/method.xml
ime/prefs/src/main/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferences.java
ime/prefs/src/test/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferencesTest.java

fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2445
fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1710

Fixes for Direct-Boot sensing

---

ime/addons/src/debug/res/xml/test_add_ons_empty.xml
ime/addons/src/main/java/com/anysoftkeyboard/addons/AddOnsFactory.java
ime/addons/src/test/java/com/anysoftkeyboard/addons/AddOnsFactoryTest.java
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/ExternalDictionaryFactory.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardFactory.java
ime/app/src/main/java/com/menny/android/anysoftkeyboard/AnyApplication.java
ime/prefs/src/main/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferences.java
ime/prefs/src/main/java/com/anysoftkeyboard/prefs/RxSharedPrefs.java
ime/prefs/src/main/res/values/test_values.xml
ime/prefs/src/test/java/com/anysoftkeyboard/prefs/DirectBootAwareSharedPreferencesTest.java
ime/prefs/src/test/java/com/anysoftkeyboard/prefs/RxSharedPrefsTest.java

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1710
Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2445

Direct boot fixes

---

.github/workflows/checks.yml
gradle/android_general.gradle
ime/app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java
ime/app/src/main/play/release-notes/en-US/alpha.txt
scripts/ci/ci_check_lint.sh

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3142
Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2984

Various fixes

---

addons/languages/persian/pack/src/main/res/xml/persian_qwerty.xml

Change the default keyWidth and match the most keys attribute.
The total kewidth of the bottom row was 105% after adding change layout button (sorry my mistake) and a part of the Enter key was out of screen. change the keywidth of the bottom row keys to be 100% totally.

Set the total keywidth of bottom row keys to 100

---

buildSrc/src/main/java/Parser.java

this will help solving issues where FS/encoding changes these

Using character number rather than character

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboard.java
ime/app/src/main/res/drawable/clipboard_action_strip_icon.xml
ime/app/src/main/res/layout/clipboard_suggestion_action.xml
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardClipboardTest.java

Longer showing clipboard action icon

---

addons/languages/english/pack/src/main/res/xml/qwerty.xml

I have added the character þ as a popup character to key p

Added þ as popup character to key p

---

ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/KeyboardViewContainerView.java
ime/app/src/main/res/layout/main_keyboard_layout.xml
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/KeyboardViewContainerViewTest.java

This will reduce accidental tapping on the candidate-view

Offsetting the top of the keyboard

---

api/src/main/java/com/anysoftkeyboard/api/KeyCodes.java
ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/LayoutSwitchAnimationListener.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPopText.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPressEffects.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSwipeListener.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/java/com/anysoftkeyboard/ui/tutorials/VersionChangeLogs.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGesturesTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGimmicksTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardKeyboardPersistentLayoutTest.java
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardPopTextTest.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSwitcherTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSwitchingTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardPressEffectsTest.java
ime/build.gradle
scripts/image_layering.py

No space swap after punctuation from a different keyboard

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/test/java/com/anysoftkeyboard/TestInputConnection.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java

Ensure we only update position if inside word

---

addons/languages/hindi/pack/src/main/res/xml/hindi_inscript.xml

Consider updating Hindi add-on so it can become usable

Added missing characters for Hindi language

---

.github/actions/auto_approval/action.yml
.github/actions/auto_approval/dist/index.js
.github/actions/auto_approval/index.js
.github/actions/auto_approval/package-lock.json
.github/actions/auto_approval/package.json
.github/workflows/auto_approve.yml
.gitignore

Imported from https://github.com/AnySoftKeyboard/actions_playground/tree/main/.github/actions/auto_approval

auto-approval GH action

---

.eslintignore
.eslintrc
.github/actions/auto_approval/action.yml
.github/actions/auto_approval/index.js
.github/actions/auto_approval/package.json
.github/workflows/auto_approve.yml
.github/workflows/checks.yml
.gitignore
.prettierignore
.prettierrc
package-lock.json
package.json

Code imported from https://github.com/AnySoftKeyboard/actions_playground

auto-approval for local PRs

---

ime/app/src/main/java/com/anysoftkeyboard/dictionaries/Suggest.java
ime/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestImpl.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/settings_keys_dont_translate.xml
ime/app/src/main/res/values/strings.xml
ime/app/src/main/res/xml/prefs_dictionaries.xml
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardDictionaryEnablingTest.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/dictionaries/SuggestTest.java
ime/dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/WordComposer.java
ime/dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/WordsSplitter.java
ime/dictionaries/src/test/java/com/anysoftkeyboard/dictionaries/WordComposerTest.java
ime/dictionaries/src/test/java/com/anysoftkeyboard/dictionaries/WordsSplitterTest.java

- Going over all permutations of splitting (assuming a character is either SPACE or not)
- pref option to enable/disable

Improving Words-Split mechanism

---

ime/app/src/main/java/com/anysoftkeyboard/saywhat/EasterEggs.java

fixed DavidBowieEasterEgg() dead link

---

config/checkstyle/checkstyle.xml
ime/app/src/main/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetector.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/MiniKeyboardActionListener.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/OnKeyboardActionListener.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
ime/app/src/main/java/com/anysoftkeyboard/quicktextkeys/ui/RecordHistoryKeyboardActionListener.java
ime/app/src/test/java/com/anysoftkeyboard/TestInputConnection.java
ime/app/src/test/java/com/anysoftkeyboard/TestableAnySoftKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/gesturetyping/GestureTypingDetectorTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java
ime/base-test/src/main/java/com/anysoftkeyboard/rx/TestRxSchedulers.java

Discards gestures that are either too short or too quick.

Introducing meaningful gesture detection. Fixes #3615

---

addons/languages/english/pack/src/main/res/xml/qwerty_with_symbols.xml

for the same reasons as my merge request #3625 . these diacritics are also used in welsh sometimes

add extra diacritics to popup options for w and y

---

ime/app/src/debug/res/xml/test_ext_kbd_row_with_mode_change.xml
ime/app/src/debug/res/xml/test_ext_kbd_row_with_symbols.xml
ime/app/src/debug/res/xml/test_ext_kbd_row_without_symbols_or_mode_change.xml
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyPopupKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/ExternalAnyKeyboard.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/GenericRowKeyboardTest.java

Show pop-up of symbols layout with long-pressing mode-switch

---

.github/workflows/checks.yml
.github/workflows/generate_contributors_list.yml
.github/workflows/localization_update.yml
.github/workflows/packs_md_update.yml
.github/workflows/third_party_update.yml
scripts/generate_contributors_md.sh

Fail when contributors generation fails

---

ime/app/src/main/res/values-en-rGB/currency_data.xml

Just make the pound (£) sign the default currency for Great Britain
Closes #3463

Add GB region for localisation

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardColorizeNavBar.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardColorizeNavBarTest.java

This will result in less flickers of the UI, since we are not changing the padding while the UI is shown.

Draw-Behind modification only onStart

---

ime/dictionaries/src/main/java/com/anysoftkeyboard/dictionaries/WordsSplitter.java
ime/dictionaries/src/test/java/com/anysoftkeyboard/dictionaries/WordsSplitterTest.java

Ensure we do not exceed max-splits

---

ime/addons/src/main/java/com/anysoftkeyboard/addons/AddOnImpl.java
ime/addons/src/main/java/com/anysoftkeyboard/addons/AddOnsFactory.java
ime/addons/src/test/java/com/anysoftkeyboard/addons/AddOnImplTest.java
ime/addons/src/test/java/com/anysoftkeyboard/addons/AddOnsFactoryTest.java
ime/app/src/main/java/com/anysoftkeyboard/AnySoftKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardBase.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardColorizeNavBar.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardKeyboardSwitchedListener.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardSwitcher.java
ime/app/src/main/java/com/menny/android/anysoftkeyboard/AnyApplication.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardColorizeNavBarTest.java

This is a much deeper issues as we re-build many components using an irrelevant Configuration object.
This fix will include a new path for updating the Context used in AddOns.
Fixes #3786

Fix for orientation layout height

---

api/src/main/res/values/keyboard_theme_api.xml
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestions.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/AnyPopupKeyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/Keyboard.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/KeyboardCondenser.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/PointerTracker.java
ime/app/src/main/res/values/dimens.xml
ime/app/src/main/res/values/settings_defaults_dont_translate.xml
ime/app/src/main/res/values/styles_base_keyboard_theme.xml
ime/app/src/main/res/values/styles_yochees_keyboard_theme.xml

This is unrelated to the theme, it is related to the behavior of the user (how do they bounce their fingers

Removing hysteresis from Theme

---

ime/app/src/main/java/com/anysoftkeyboard/dictionaries/SuggestImpl.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardSuggestionsTest.java

next-word should be used as a hint for prioritize suggestions, not replace the typed word.

Fix next-word auto-pick bug 

---

.github/actions/codecov/upload_coverage.sh
.github/workflows/auto_approve.yml
.github/workflows/checks.yml
.github/workflows/deploy.yml
.github/workflows/deployment_promote.yml
.github/workflows/generate_contributors_list.yml
.github/workflows/localization_update.yml
.github/workflows/packs_md_update.yml
.github/workflows/third_party_update.yml
scripts/modules_sharder.py

This is required for codecov to correctly calculate diff

Giving codecov context on the change

---

.github/workflows/checks.yml
.github/workflows/generate_contributors_list.yml
.github/workflows/localization_update.yml
.github/workflows/packs_md_update.yml
.github/workflows/third_party_update.yml

this handles the 'undefined number' error.

Bumping PR creation action

---

.github/workflows/checks.yml
scripts/modules_sharder.py

Using more shards for addons

---

addons/languages/coptic/apk/build.gradle

Also, fixed a couple of things in Play Console

Fixing closed channel for Coptic

---

buildSrc/src/main/java/Parser.java

This prevents android-studio from compiling this nice project.

android-studio complains that these CP1250 chars are not utf8

---

addons/languages/english/pack/dictionary/prebuilt/additionals.xml
ime/dictionaries/jnidictionaryv2/src/main/jni/source/dictionary.cpp

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3317

Higher freq for terminal typed words

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardSwipeListener.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardView.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AskGestureEventsListener.java
ime/app/src/main/res/values/dimens.xml
ime/app/src/test/java/com/anysoftkeyboard/AnySoftKeyboardGesturesTest.java
ime/app/src/test/java/com/anysoftkeyboard/ViewTestUtils.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBaseTest.java
ime/app/src/test/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewTest.java

Dismiss keyboard when swiping beyond the bottom of the keyboard

---

ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardNightMode.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardPowerSaving.java
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardThemeOverlay.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/AnyKeyboardViewBase.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/CandidateView.java
ime/app/src/main/java/com/anysoftkeyboard/keyboards/views/KeyboardViewContainerView.java
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/KeyboardThemeSelectorFragment.java
ime/overlay/src/main/java/com/anysoftkeyboard/overlay/OverlayData.java
ime/overlay/src/main/java/com/anysoftkeyboard/overlay/OverlayDataImpl.java
ime/overlay/src/main/java/com/anysoftkeyboard/overlay/OverlayDataNormalizer.java
ime/overlay/src/main/java/com/anysoftkeyboard/overlay/OverlyDataCreatorForAndroid.java
ime/overlay/src/main/java/com/anysoftkeyboard/overlay/ThemeOverlayCombiner.java
ime/overlay/src/test/java/com/anysoftkeyboard/overlay/OverlayDataNormalizerTest.java
ime/overlay/src/test/java/com/anysoftkeyboard/overlay/OverlayDataOverriderTest.java
ime/overlay/src/test/java/com/anysoftkeyboard/overlay/OverlayDataTest.java
ime/overlay/src/test/java/com/anysoftkeyboard/overlay/ThemeOverlayCombinerTest.java

Fixes issues where the text-color is not compatible with the keyboard background (vs text-color compared to key-background)

Better colorized theme

---

addons/languages/french/apk/src/main/play/listings/en-US/full-description.txt
addons/languages/french/apk/src/main/play/release-notes/en-US/alpha.txt
addons/languages/french/pack/src/main/res/values-fr/strings.xml
addons/languages/french/pack/src/main/res/values/strings.xml
addons/languages/french/pack/src/main/res/xml/ergol.xml
addons/languages/french/pack/src/main/res/xml/french_keyboards.xml

The layout is defined as : "Ergonomic keyboard optimised for French, English and code"
Closes #4052

Add french Ergol-L keyboard layout

---

ime/app/proguard-anysoftkeyboard.txt
ime/app/src/main/java/com/anysoftkeyboard/ime/AnySoftKeyboardWithGestureTyping.java
ime/app/src/test/java/com/anysoftkeyboard/ime/AnySoftKeyboardGestureTypingTest.java
ime/base/src/main/java/com/anysoftkeyboard/base/utils/GenericAutoClose.java
ime/base/src/test/java/com/anysoftkeyboard/base/utils/GenericAutoCloseTest.java

Fix dead IC in gesture-typing

---

ime/app/src/main/java/com/anysoftkeyboard/ui/settings/setup/SetupSupport.java
ime/app/src/test/java/com/anysoftkeyboard/ui/settings/setup/SetUpKeyboardWizardTest.java
ime/app/src/test/java/com/anysoftkeyboard/ui/settings/setup/SetupSupportTest.java
ime/app/src/test/java/com/anysoftkeyboard/ui/settings/setup/WizardPageEnableKeyboardFragmentTest.java
ime/app/src/test/java/com/menny/android/anysoftkeyboard/InputMethodManagerShadow.java
ime/app/src/test/java/com/menny/android/anysoftkeyboard/LauncherSettingsActivityTest.java

Fix Settings.Secure.ENABLED_INPUT_METHODS not readable on SDK 34+

Enabled input methods fix

---

ime/app/src/main/java/com/anysoftkeyboard/ui/SendBugReportUiActivity.java
ime/app/src/main/res/layout/send_crash_log_ui.xml

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/4060

Fix crash-report subtitle and header

---

addons/base/apk/src/main/java/com/anysoftkeyboard/addon/apk/MainActivity.kt
build.gradle
buildSrc/build.gradle
ime/app/src/main/java/com/anysoftkeyboard/ui/settings/MainSettingsActivity.java
ime/base/src/main/java/com/anysoftkeyboard/base/utils/CompatUtils.java
ime/pixel/src/main/res/values-v35/app_styles.xml
ime/pixel/src/main/res/values/app_styles.xml

Specifically, fix edge-to-edge issue in API35 - issue https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/4161

General fixes

---

.github/workflows/localization_update.yml
ime/app/src/main/play/release-notes/en-US/alpha.txt
ime/app/src/main/res/navigation/settings_main.xml
ime/releaseinfo/src/main/java/com/anysoftkeyboard/releaseinfo/VersionChangeLogs.java

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/4149
Closes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/4167

Fix changelog stuff

---

.github/actions/deploy/deploy.sh
build.gradle

Reverts AnySoftKeyboard/AnySoftKeyboard#4170
We have a few add-on packages that are not publishable, and do not have a "release" task

Revert "Less tasks in addon-publish"

---

.github/actions/deploy/deploy.sh
.github/workflows/deploy.yml
.github/workflows/deployment_promote.yml

This solves the issue of missing bazelisk in the container. GH runners have that

deploy without docker

---

js/localization_tools/BUILD.bazel
js/localization_tools/replace_ellipsis.test.ts
js/localization_tools/replace_ellipsis.ts

fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/4191

unit-tests for replaceEllipsisInFile

---

addons/languages/russian2/pack/src/main/res/xml/cyrillic_qwerty.xml

Fixes https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/4242

Adding missing popup character for Cyrillic
